### ISSUE TITLE
Selecting Send bootstrap msg crushing Node Red.

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal#26]
When select: Send bootstrap msg, crushing Node-Red on Deploy or reboot.

![image](https://user-images.githubusercontent.com/7469537/138381438-24a5cc27-6eb7-472d-8578-bee18088c1fe.png)

Node-Red v 2.0.6 runs in Docker.

**Comment by flic** [comment]
Sorry 'bout that, fixed in 1.4.1

**Comment by alexsahka** [comment]
Thanks, could you update the NoderRed repository?
![image](https://user-images.githubusercontent.com/7469537/138495138-a1414402-4f5f-4f81-92c6-1dd2f0326f26.png)

**Comment by flic** [comment]
It's updated on NPM, so I'm guessing it just takes some time.

https://www.npmjs.com/package/node-red-contrib-hal

**Comment by alexsahka** [comment]
Oh, OK thanks!

**Comment by alexsahka** [comment]
9+ hours and still not updated for some reason, do you know the approximate update time?

**Comment by alexsahka** [comment]
Seems like you need to refresh something somewhere in NPM. The latest version of node-red-contrib-hal is 1.3.2 in Node Red. But in the NPM last before 1.4.1 was 1.4.0 updated 10 months ago.
![image](https://user-images.githubusercontent.com/7469537/138534475-a2a97cf5-6140-4aa3-b896-3bfe999c9659.png)

Maybe this would be helpful?
https://discourse.nodered.org/t/how-to-force-update-node-from-www-npmjs-com-to-node-red-pallet/20000

**Comment by flic** [comment]
You're right, I just found this on nodered.org:

![Skärmavbild 2021-10-23 kl  08 41 40](https://user-images.githubusercontent.com/400673/138545781-b835fd47-d62b-4057-bc95-5b97c3700f81.png)

I've updated the library manually and now it shows 1.4.1, but I still see 1.3.2 in Manage palette in Node-RED itself. I'll give it a few hours and check back.

If you're tired of waiting, just run the following in your node-red installation:

cd ~/.node-red
npm install node-red-contrib-hal

**Comment by alexsahka** [comment]
Thank you for your work!
